apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: ai-focus
  version: v1.0.0

images:
- name: ghcr.io/jisujit/ai-focus
  newTag: latest
