apiVersion: v1
kind: Service
metadata:
  name: ai-focus-service
  labels:
    app: ai-focus
spec:
  selector:
    app: ai-focus
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
